### ISSUE TITLE
generated one BAM file for each single cell

### ISSUE THREAD

**Issue by ghost** [YiPeng-Gao/scDaPars#7] opened 2021-05-26 03:10 UTC
Hello, can you provide an operation for this step?
Write a script to operate this step. The 1G file is split into files for each cell. This process takes 10h.
Each bam file will be split into thousands of files

![image](https://user-images.githubusercontent.com/54733697/119596958-b6c53b80-be12-11eb-83a2-5989539bedf5.png)

**Comment by YiPeng-Gao** [comment] 2021-05-26 03:17
You can use "pysam.AlignmentFile" to open one bam file for each single cell and then extract and combine reads based on the cell barcode. For example: pysam.AlignmentFile("cell_bam_files/cell.bam", "wb", template = bam_file)

**Comment by ghost** [comment] 2021-05-26 07:40
What is the software parameter setting of UMI-tools?

After using filterbam to filter bam files,   remove reads with duplicated UMIs using UMI-tools dedup
After setting the corresponding parameters, UMi displays the error content:
WARNING The BAM did not contain any valid reads/read pairs for deduplication

![image](https://user-images.githubusercontent.com/54733697/119621338-94461900-be38-11eb-8b8e-54452cc37dc1.png)

**Comment by YiPeng-Gao** [comment] 2021-05-26 08:22
> What is the software parameter setting of UMI-tools?
> 
> After using filterbam to filter bam files, remove reads with duplicated UMIs using UMI-tools dedup
> After setting the corresponding parameters, UMi displays the error content:
> WARNING The BAM did not contain any valid reads/read pairs for deduplication
> 
> ![image](https://user-images.githubusercontent.com/54733697/119621338-94461900-be38-11eb-8b8e-54452cc37dc1.png)

You can use the command "umi_tools dedup -I input.bam -S output.bam --method=unique --extract-umi-method=tag --umi-tag=UB --cell-tag=CB" to remove UMI duplcation. However, I am not the developer for UMI-tools, so I cannot help you debug your code. I will only answer questions related to the scDaPars algorithm.

**Comment by huangrongbioinfomation** [comment] 2021-05-26 09:24
Run 87M files, but the speed is relatively slow, run 4h, analyze files to 1/4

#!/usr/bin/env python
# -*- coding:utf-8 -*-

import pysam
import sys
import os
import re
import threading

unsplit1 = sys.argv[1]
unsplit = str(unsplit1)

out_dir1 = sys.argv[2]
out_dir = str(out_dir1)

def run(unsplit_file,out_dir):
    itr = 0
    CB_hold = 'unset'
    samfile = pysam.AlignmentFile(unsplit_file, "rb")
    for read in samfile.fetch(until_eof=True):
        if 'CB' in str(read):
            print("read:" + str(read))
            CB_itr = read.get_tag('CB')
            print("CB_itr : "+str(CB_itr))
            if( CB_itr!=CB_hold or itr==0):
                if(itr!=0):
                    split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
                    split_file.close()     
                CB_hold = CB_itr
                itr = itr + 1
                split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
                split_file.write(read) 
    split_file.close()
    samfile.close()

if __name__ == '__main__':
    for i in range(5):
        t = threading.Thread(target=run(unsplit,out_dir))
        t.start()

**Comment by YiPeng-Gao** [comment] 2021-05-26 09:32
> Run 87M files, but the speed is relatively slow, run 4h, analyze files to 1/4
> 
> #!/usr/bin/env python
> 
> # -_- coding:utf-8 -_-
> import pysam
> import sys
> import os
> import re
> import threading
> 
> unsplit1 = sys.argv[1]
> unsplit = str(unsplit1)
> 
> out_dir1 = sys.argv[2]
> out_dir = str(out_dir1)
> 
> def run(unsplit_file,out_dir):
> itr = 0
> CB_hold = 'unset'
> samfile = pysam.AlignmentFile(unsplit_file, "rb")
> for read in samfile.fetch(until_eof=True):
> if 'CB' in str(read):
> print("read:" + str(read))
> CB_itr = read.get_tag('CB')
> print("CB_itr : "+str(CB_itr))
> if( CB_itr!=CB_hold or itr==0):
> if(itr!=0):
> split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
> split_file.close()
> CB_hold = CB_itr
> itr = itr + 1
> split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
> split_file.write(read)
> split_file.close()
> samfile.close()
> 
> if **name** == '**main**':
> for i in range(5):
> t = threading.Thread(target=run(unsplit,out_dir))
> t.start()

It is slow, but yours seems too slow. You can first open the number of bam files as the same number of cells without closing. Then write reads into each of those empty bam files. It will save you some time.

**Comment by YiPeng-Gao** [comment] 2021-05-26 09:36
> Run 87M files, but the speed is relatively slow, run 4h, analyze files to 1/4
> 
> #!/usr/bin/env python
> 
> # -_- coding:utf-8 -_-
> import pysam
> import sys
> import os
> import re
> import threading
> 
> unsplit1 = sys.argv[1]
> unsplit = str(unsplit1)
> 
> out_dir1 = sys.argv[2]
> out_dir = str(out_dir1)
> 
> def run(unsplit_file,out_dir):
> itr = 0
> CB_hold = 'unset'
> samfile = pysam.AlignmentFile(unsplit_file, "rb")
> for read in samfile.fetch(until_eof=True):
> if 'CB' in str(read):
> print("read:" + str(read))
> CB_itr = read.get_tag('CB')
> print("CB_itr : "+str(CB_itr))
> if( CB_itr!=CB_hold or itr==0):
> if(itr!=0):
> split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
> split_file.close()
> CB_hold = CB_itr
> itr = itr + 1
> split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,itr), "wb", template=samfile)
> split_file.write(read)
> split_file.close()
> samfile.close()
> 
> if **name** == '**main**':
> for i in range(5):
> t = threading.Thread(target=run(unsplit,out_dir))
> t.start()

You can use this code

**Closed as completed by YiPeng-Gao** 2021-05-26 09:36 UTC

**Comment by ghost** [comment] 2021-05-26 10:03
Do I need to split each bam file into each cell bam file? Can it be split into bam files of a single chromosome for analysis?
In this step, splitting bam will consume more resources and more time
If there are many samples, the operation will consume more time and the steps will be more complicated
How long did you spend on this step?

**Comment by YiPeng-Gao** [comment] 2021-05-26 10:06
> Do I need to split each bam file into each cell bam file? Can it be split into bam files of a single chromosome for analysis?
> In this step, splitting bam will consume more resources and more time
> If there are many samples, the operation will consume more time and the steps will be more complicated
> How long did you spend on this step?

No you cannot just separate into chromosomes, you have to separate into different cells. It takes me couple of hours to perform this one in a file contain ~3000 single cells.

**Comment by ghost** [comment] 2021-05-26 10:09
Can you submit the code of the operation?

**Comment by huangrongbioinfomation** [comment] 2021-05-27 02:05
Hello, I would like to consult you about the use of pysam.AlignmentFile,
When running the script, the problem is to create a new directory. The previously existing files will also be overwritten again.

`#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pysam
import sys
import os
import re
import threading
unsplit_file = sys.argv[1]
out_dir = sys.argv[2]

def run(unsplit_file,out_dir):
    CB_hold = 'unset'
    samfile = pysam.AlignmentFile(unsplit_file, "rb")
    for read in samfile:
        if 'CB' in str(read):  # filter not contain CB
            CB_itr = read.get_tag('CB') #get barcode
            split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,CB_itr), "wb", template=samfile)
            split_file.write(read)
    return

if __name__ == '__main__':
    for i in range(10):
        t = threading.Thread(target=run(unsplit_file,out_dir))
        t.start()`

**Comment by huangrongbioinfomation** [comment] 2021-05-27 02:06
Hello, I would like to consult you about the use of pysam.AlignmentFile,
When running the script, the problem is to create a new directory. The previously existing files will also be overwritten again.

`#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pysam
import sys
import os
import re
import threading
unsplit_file = sys.argv[1]
out_dir = sys.argv[2]

def run(unsplit_file,out_dir):
    CB_hold = 'unset'
    samfile = pysam.AlignmentFile(unsplit_file, "rb")
    for read in samfile:
        if 'CB' in str(read):  # filter not contain CB
            CB_itr = read.get_tag('CB') #get barcode
            split_file = pysam.AlignmentFile('%s/CB_%s.bam'%(out_dir,CB_itr), "wb", template=samfile)
            split_file.write(read)
    return

if __name__ == '__main__':
    for i in range(10):
        t = threading.Thread(target=run(unsplit_file,out_dir))
        t.start()`

**Comment by huangrongbioinfomation** [comment] 2021-05-27 05:10
split_file = pysam.AlignmentFile(name, "wb", template=samfile) 
This line of code does not have the function of additional writing,
```
with open(barcode) as barcodeliness:
    barcodelines = barcodeliness.readlines()
    for barcodeline in barcodelines:
        #print("barcodeline:"+str(barcodeline))
        keyvalue = barcodeline.strip()
        print("keyvalue:"+str(keyvalue))
        valuelist = bamdict[keyvalue]
        name = out_dir +"/CB_"+keyvalue+".bam"
        for valuelisti in valuelist:
            split_file = pysam.AlignmentFile(name, "wb", template=samfile) # 含有追加写入的功能
            split_file.write(read)
```

**Comment by huangrongbioinfomation** [comment] 2021-05-27 06:10
outputliness = pysam.AlignmentFile(name, "wb", template = samfile, this code line does not have the function of appending 
content to write text.
How to implement a similar function, write(file, "a)
```
#!/usr/bin/env python
# -*- coding:utf-8 -*-

import pysam
import sys
import os
import re

unsplit_file = sys.argv[1]
out_dir = sys.argv[2]

bamdict = {}
samfile = pysam.AlignmentFile(unsplit_file, "rb")  
for read in samfile.fetch(until_eof=True):
    print("read: "+ str(read))
    if read.has_tag('CB'):  # contain CB
        barcode = read.get_tag('CB')
        name =  out_dir +"/CB_"+barcode+".bam"
        outputliness = pysam.AlignmentFile(name, "wb", template=samfile) 
        outputliness.write(read)
```
